In [ ]:
"""Numpy Part-1"""

In [1]:
import numpy as np

In [5]:
l = [1,2,3,4]
ar = np.array(l)
print(ar)

[1 2 3 4]


In [6]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]]) # it is 2-d array

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l) # same as np.array()

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l) # same as np.array()

array([1, 2, 3, 4])

In [11]:
b = np.matrix(l) # matrix is a subset of array

In [12]:
b # matrix is by default 2-d array

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b) # this will not convert matrix into array because matrix is already a subset of array

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
a

array([1, 2, 3, 4])

In [16]:
c = a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
c[0] = 100 # changes made into 'c' will be reflected in 'a' too AND vice-versa
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [23]:
a[1] = 200
a

array([100, 200,   3,   4])

In [24]:
d #nothing changes in 'd' when we change in 'a'

array([100,   2,   3,   4])

In [25]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j,(4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [29]:
iterable = (i*i for i in range(5)) # this is iter function
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring("12 23 34", sep = " ") # will create an array from string

array([12., 23., 34.])

In [ ]:
# Numpy - Data Types

In [36]:
ar = np.array([1,2,3,4])

In [37]:
ar

array([1, 2, 3, 4])

In [38]:
ar.ndim # use to find dimension of array

1

In [39]:
ar.size # use to find size of array

4

In [40]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [41]:
ar2.shape # tells us about the shape
# OUTPUT: (2,3) means there is 2 row and 3 columns

(2, 3)

In [43]:
np.arange(1.3,5.6) # will generate floating numbers from 1.3 till 5.6 with jump = 1

array([1.3, 2.3, 3.3, 4.3, 5.3])

In [44]:
np.arange(1.3,5.6, 0.4) # will generate floating numbers from 1.3 till 5.6 with jump = 0.4

array([1.3, 1.7, 2.1, 2.5, 2.9, 3.3, 3.7, 4.1, 4.5, 4.9, 5.3])

In [45]:
list(np.arange(1.3,5.6, 0.4)) # will generate and store this in list

[1.3,
 1.7000000000000002,
 2.1000000000000005,
 2.5000000000000004,
 2.9000000000000004,
 3.3000000000000007,
 3.700000000000001,
 4.1000000000000005,
 4.500000000000001,
 4.900000000000001,
 5.300000000000002]

In [3]:
np.linspace(1,5,10) # will generate 10 data between 1 to 5 and sb equally divided hga

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [4]:
np.zeros(5) # WILL GENERATE 1-D ARRAY WITH 5 DATA ITEMS WHOSE VALUE = 0

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4)) # will generate 2-d array (dimension = (3,4)) with all the values = 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((3,4,2)) # we have 4*2 , 3 such kind of arrays

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2,3)) # will create 2*3 array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
on = np.ones((2,3,3)) # will create 3*3, 2 such kind of arrays

In [13]:
on + 5 # will add 5 to each of the element

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [14]:
on * 4 # will multiply each element with 4

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [16]:
np.empty((2,3)) # will create an empty array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(4) # will create an identity matrix of dimension 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [21]:
np.logspace(2,5,10,base=2) # similar to linspace but it will give logarithmic value

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [22]:
"Most use concept of Numpy"
np.random.randn(3,4) # will give array of size 3*4 with random values

array([[-0.51757098,  0.08160756, -0.78611662, -0.37363104],
       [ 0.64425812, -0.96811879, -1.73056168, -0.35991192],
       [-1.07800569,  1.1121852 ,  0.94478684, -1.37175688]])

In [23]:
arr = np.random.randn(2,3)

In [4]:
import pandas as pd

In [26]:
pd.DataFrame(arr)

0         1         2
0  0.210804  1.809304  0.458003
1 -0.254013 -0.459779 -0.337131

In [27]:
np.random.rand(3,4)

array([[0.8508673 , 0.80112106, 0.46282118, 0.86716077],
       [0.04091731, 0.8608774 , 0.46877952, 0.6587793 ],
       [0.21011103, 0.79688254, 0.9042691 , 0.7625014 ]])

In [ ]:
"""
Understand difference between 'randn' & 'rand' function in Numpy
"""

In [30]:
np.random.randint(1,100,(3,4)) # will give integer between 1 and 100 and fill it in 3*4 array

array([[55, 61,  7, 93],
       [37, 28, 95,  6],
       [15,  6, 42, 75]])

In [5]:
pd.DataFrame(np.random.randint(1,100,(10,10))) # will generate array between 1 & 100 of size 10*10 and convert it into data frame

0   1   2   3   4   5   6   7   8   9
0  56  82  18  43  99  57  57  85   3  73
1  95  92  60  97  21  12  35  86  63  72
2  85  74  50  99  82   2  34  93  91  73
3  80  65  63  21  26  72  57  22  70  59
4  99  84   3  84  98  93  95  63  92  32
5  61  35  58   6  53  85   3  63   1  23
6  37  11  53  31  17  70  12   1  99   2
7   4  61  36  38  98  78  85  33  68  85
8  45  14  13  38  94  41  35  39  45  50
9  93  85  13  15  90  62  65  87   6  94

In [6]:
arr = np.random.randint(1,100,(3,4))

In [7]:
arr

array([[39, 24, 54, 24],
       [39, 60, 51, 57],
       [63, 57, 57, 13]])

In [8]:
arr.reshape(6,2) # will reshape "arr" array into 6 rows and 2 columns

array([[39, 24],
       [54, 24],
       [39, 60],
       [51, 57],
       [63, 57],
       [57, 13]])

In [9]:
arr1 = np.random.randint(1,100,(5,5))

In [10]:
arr1

array([[94, 66, 30, 21, 82],
       [85, 78, 38, 80, 37],
       [79, 37, 55, 33,  8],
       [44,  6, 14, 20,  1],
       [71, 69, 30, 20, 32]])

In [11]:
arr1>50 # will show data in arr1 where arr1 value is > 50

array([[ True,  True, False, False,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False, False]])

In [12]:
arr1[arr1>50] # will return only those value which is greater than 50

array([94, 66, 82, 85, 78, 80, 79, 55, 71, 69])

In [13]:
arr1

array([[94, 66, 30, 21, 82],
       [85, 78, 38, 80, 37],
       [79, 37, 55, 33,  8],
       [44,  6, 14, 20,  1],
       [71, 69, 30, 20, 32]])

In [15]:
# we want to data from 2 & 3 rows and 1st & 2nd column only
arr1[2:4,[1,2]] # slicing

array([[37, 55],
       [ 6, 14]])

In [16]:
arr1[0][0]

94

In [17]:
arr1[0][0] = 500 # manipulating data in an array

In [18]:
arr1

array([[500,  66,  30,  21,  82],
       [ 85,  78,  38,  80,  37],
       [ 79,  37,  55,  33,   8],
       [ 44,   6,  14,  20,   1],
       [ 71,  69,  30,  20,  32]])

In [19]:
a1 = np.random.randint(1,5,(3,3))
a2 = np.random.randint(1,5,(3,3))

In [20]:
a1

array([[4, 4, 4],
       [2, 3, 4],
       [3, 1, 2]])

In [21]:
a2

array([[3, 3, 4],
       [2, 2, 3],
       [1, 2, 1]])

In [22]:
a1+a2 # will sum both the array

array([[7, 7, 8],
       [4, 5, 7],
       [4, 3, 3]])

In [23]:
a1-a2

array([[ 1,  1,  0],
       [ 0,  1,  1],
       [ 2, -1,  1]])

In [24]:
a1/a2

array([[1.33333333, 1.33333333, 1.        ],
       [1.        , 1.5       , 1.33333333],
       [3.        , 0.5       , 2.        ]])

In [25]:
a1*a2 # this is simple index multiplication and not a matrix multiplication

array([[12, 12, 16],
       [ 4,  6, 12],
       [ 3,  2,  2]])

In [26]:
a1@a2 # this will give matrix multiplication

array([[24, 28, 32],
       [16, 20, 21],
       [13, 15, 17]])

In [27]:
a1 + 100 # will add 100 to each element of array

array([[104, 104, 104],
       [102, 103, 104],
       [103, 101, 102]])

In [28]:
a1 ** 2 # sbka power 2 se badha dega

array([[16, 16, 16],
       [ 4,  9, 16],
       [ 9,  1,  4]])

In [66]:
~a1 # negation of a1

array([[-5, -5, -5],
       [-3, -4, -5],
       [-4, -2, -3]])

In [67]:
a1>a2

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [29]:
# NUMPY - BROADCASTING

In [39]:
a3 = np.zeros((3,3))

In [40]:
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
row = np.array([1,2,3])

In [42]:
row

array([1, 2, 3])

In [43]:
a3 + row # will add row to each row of a3 array and this is known as broadcasting

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:
a4 = np.random.randint(1,4,(3,3))

In [45]:
np.sqrt(a4) # will find sqrt of each element is array

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [46]:
"""
Numpy: Part-2
"""

'\nNumpy: Part-2\n'

In [ ]:
# MANIPULATING ARRAY

In [47]:
arr = np.random.randint(1,10,(3,4))

In [48]:
arr

array([[2, 7, 6, 2],
       [5, 7, 1, 3],
       [4, 6, 4, 3]])

In [ ]:
# now we want to reshape our array
# there is 3 rows and 4 columns & their multiplication is 12
# In order to reshape it one condition must satisfy
# Condition: multiplication of rows and columns must be 12

In [49]:
arr.reshape(2,6) # 2*6 = 12

array([[2, 7, 6, 2, 5, 7],
       [1, 3, 4, 6, 4, 3]])

In [50]:
arr.reshape(4,3) # 4*3 = 12

array([[2, 7, 6],
       [2, 5, 7],
       [1, 3, 4],
       [6, 4, 3]])

In [51]:
# Transposing an array
arr.T

array([[2, 5, 4],
       [7, 7, 6],
       [6, 1, 4],
       [2, 3, 3]])

In [53]:
arr.flatten()

array([2, 7, 6, 2, 5, 7, 1, 3, 4, 6, 4, 3])

In [54]:
arr1 = np.random.randint(1,10,(3,4))

In [55]:
arr1

array([[4, 5, 5, 7],
       [8, 9, 5, 8],
       [6, 8, 5, 2]])

In [56]:
arr1.ndim

2

In [57]:
np.expand_dims(arr1,axis = 1) # will increase dimension by 1 and axis = 1 means along columns

array([[[4, 5, 5, 7]],

       [[8, 9, 5, 8]],

       [[6, 8, 5, 2]]])

In [58]:
np.expand_dims(arr1,axis = 0) # will increase dimension by 1 and axis = 0 means along rows

array([[[4, 5, 5, 7],
        [8, 9, 5, 8],
        [6, 8, 5, 2]]])

In [60]:
data = np.array([[1],[2],[3]])

In [61]:
data

array([[1],
       [2],
       [3]])

In [62]:
np.squeeze(data) # will reduce dimension

array([1, 2, 3])

In [65]:
np.diag(np.array([1,2,3,4])) # diagonal element set kr dega

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# NUMPY - STRING FUNCTIONS

In [68]:
arr = np.array(['ayan','khan'])

In [70]:
arr

array(['ayan', 'khan'], dtype='<U4')

In [71]:
np.char.upper(arr) # sbko upper case mein convert kr dega

array(['AYAN', 'KHAN'], dtype='<U4')

In [72]:
np.char.title(arr)

array(['Ayan', 'Khan'], dtype='<U4')

In [73]:
np.char.capitalize(arr)

array(['Ayan', 'Khan'], dtype='<U4')

In [ ]:
# NUMPY - MATHEMATICAL FUNCTIONS

In [74]:
arr1 = np.random.randint(1,10,(3,3))

In [75]:
arr1

array([[8, 9, 8],
       [1, 9, 1],
       [8, 4, 2]])

In [76]:
np.sin(arr1)

array([[ 0.98935825,  0.41211849,  0.98935825],
       [ 0.84147098,  0.41211849,  0.84147098],
       [ 0.98935825, -0.7568025 ,  0.90929743]])

In [77]:
np.cos(arr1)

array([[-0.14550003, -0.91113026, -0.14550003],
       [ 0.54030231, -0.91113026,  0.54030231],
       [-0.14550003, -0.65364362, -0.41614684]])

In [78]:
np.tan(arr1)

array([[-6.79971146, -0.45231566, -6.79971146],
       [ 1.55740772, -0.45231566,  1.55740772],
       [-6.79971146,  1.15782128, -2.18503986]])

In [79]:
np.median(arr1)

8.0

In [80]:
np.max(arr1)

9

In [81]:
np.min(arr1)

1

In [82]:
np.std(arr1)

3.303570832737446

In [83]:
np.mean(arr1)

5.555555555555555

In [ ]:
"""
NUMPY: PART-3
"""

In [84]:
# sort, search and counting functions

In [85]:
import numpy as np

In [87]:
arr = np.array([4,6,3,2,6,7,88,32,54])

In [88]:
arr

array([ 4,  6,  3,  2,  6,  7, 88, 32, 54])

In [89]:
np.sort(arr)

array([ 2,  3,  4,  6,  6,  7, 32, 54, 88])

In [90]:
np.searchsorted(arr,5) # this will tell us that 5 will into which index in 'arr' array

4

In [92]:
arr1 = np.array([3,6,0,0,0,2,0,0])

In [93]:
np.count_nonzero(arr1) # counts non zero element in an array

3

In [94]:
arr

array([ 4,  6,  3,  2,  6,  7, 88, 32, 54])

In [95]:
np.where(arr>5) # return index where value is > 6

(array([1, 4, 5, 6, 7, 8]),)

In [96]:
np.extract(arr>5,arr) # data extract krega jaha pr bhi value > 6 hga in 'arr' array

array([ 6,  6,  7, 88, 32, 54])

In [ ]:
# NUMPY - BYTE SWAPPING

In [97]:
arr

array([ 4,  6,  3,  2,  6,  7, 88, 32, 54])

In [100]:
arr.byteswap()

array([ 288230376151711744,  432345564227567616,  216172782113783808,
        144115188075855872,  432345564227567616,  504403158265495552,
       6341068275337658368, 2305843009213693952, 3891110078048108544])

In [ ]:
# NUMPY - COPIES & VIEWS

In [101]:
arr

array([ 4,  6,  3,  2,  6,  7, 88, 32, 54])

In [102]:
a = np.copy(arr) # deep copy i.e. changes made in 'a' will not reflect in 'arr'

In [103]:
a

array([ 4,  6,  3,  2,  6,  7, 88, 32, 54])

In [111]:
a[1] = 54

In [112]:
a

array([ 4, 54,  3,  2,  6,  7, 88, 32, 54])

In [113]:
arr

array([ 4, 23,  3,  2,  6,  7, 88, 32, 54])

In [114]:
b = arr.view() # shallow copy i.e. changes made in 'b' will reflect in 'arr'

In [115]:
b

array([ 4, 23,  3,  2,  6,  7, 88, 32, 54])

In [116]:
b[1] = 65

In [117]:
b

array([ 4, 65,  3,  2,  6,  7, 88, 32, 54])

In [118]:
arr

array([ 4, 65,  3,  2,  6,  7, 88, 32, 54])

In [ ]:
" NUMPY: MATRIX"

In [1]:
import numpy.matlib as nm

In [2]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [4]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
"NUMPY: LINEAR ALGEBRA"

In [6]:
import numpy as np

a1 = nm.random.randint(1,10,(3,3))
a2 = nm.random.randint(1,10,(3,3))

In [7]:
a1

array([[7, 7, 3],
       [4, 8, 9],
       [4, 2, 1]])

In [8]:
a2

array([[6, 8, 7],
       [8, 9, 2],
       [8, 2, 5]])

In [9]:
nm.dot(a1,a2) # same as matrix multiplication

array([[122, 125,  78],
       [160, 122,  89],
       [ 48,  52,  37]])

In [10]:
a1@a2 # matrix multiplication

array([[122, 125,  78],
       [160, 122,  89],
       [ 48,  52,  37]])